# -*- coding: utf-8 -*-
"""assigment_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AtRX21daIG0LUyHaebPXQwFBAUyySpVE
"""

def sansür(sansürlü,sesli):
  n=0
  for i in sansürlü:
    if i =="*":
        sansürlü=sansürlü.replace("*",sesli[n],1)
        n+=1
  return sansürlü     
print(sansür("pyth*n", "o"))
print(sansür("*r*b*m* p*rk *tt*m","aaaıaei"))