# -*- coding: utf-8 -*-
"""assigment_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fvYKIn53jko4Sa1SEj6bfnxM7nKsCmay

Girdisi string olan ifadenin içerisindeki harflerin türkçe alfabesindeki yerlerini bulup, hepsinin değerlerini toplayıp sonuç çiftse True tekse False yazdıran bir fonksiyon yazınız.
"""

def kelime_çift_mi(cümle):
  buyuk="ABCÇDEFGĞHIİJKLMNOÖPRSŞTUÜVYZ"
  kucuk="abcçdefgğhıijklmnoöprsştuüvyz"
  toplam=0
  for i in cümle:
    if i in buyuk:
      toplam+=buyuk.index(i)+1
    elif i in kucuk:
      toplam+=kucuk.index(i)+1
    
  if toplam % 2 ==0:
    return True
  else:
    return False

print(kelime_çift_mi("Bilgisayar"))