# -*- coding: utf-8 -*-
"""assigment_3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uGzC3GwnRbydCpYRV-u8eeIz5FjPibPl

Sudoku her 3-3 lük karede 1'den 9'a kadar olan rakamların birer kez yer alması gerektiği temeline dayanan bir zeka oyunudur. Su doku olup olmadığını inceleyen, sudoku ise True değil ise False değeri veren bir fonksiyon yazalım.
"""

def sudoku_mu(sudoku):
  toplam=0
  yen_sudoku=[]
  for i in sudoku:
    if i[0]==i[1] or i[0]==i[2] or i[1]==i[2]:
      return False
    for k in i:
      yen_sudoku.append(k)
      if len(set(yen_sudoku))!=9:
        return False
      if k<1 or k>9:
        return False
      else:
        toplam+=k
  if toplam==45:
    return True
  else:
    return False
                 
print(sudoku_mu([[7, 6, 2], [7, 6, 2], [7, 6, 2]]))
print(sudoku_mu([[1, 5, 2], [8, 9, 8], [3, 5, 6]]))