# -*- coding: utf-8 -*-
"""assigment_4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1F2nx1EU_jyVjrn3TqOkJ7LZffSH22qnH

Satrançta vezirler hangi durumda birbirini yer. Vezir yatay,dikey ve çapraz olarak hareket edebiliyor.
"""

def vezir(oyuncular):
  p1= oyuncular[0]
  p2=oyuncular[1]
  if p1[0]==p2[0] or p1[1]==p2[1]:
    return True
  tahtax = "ABCDEFGH"
  tahtay = "12345678"
  mesafex = abs(tahtax.index(p1[0]) - tahtax.index(p2[0]))
  mesafey = abs(tahtay.index(p1[1]) - tahtay.index(p2[1]))
  if mesafex == mesafey:
    return True
  else:
    return False